baseurl = "http://redstalker.com/"
languageCode = "en-us"
title = "Redstalker"
copyright = "Copyright (c) 2013 - 2015, Redstalker.com; All Rights Reserved."
disqusShortname = "redstalker"
MetaDataFormat = "yaml"

[author]
    name = "Nicholas J"
    github = "taion809"
    twitter = "taion809"
    gaID = "UA-43022143-1"

[permalinks]
    # Change the permalink format for the 'post' content type.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    tag = "tags"
    topic = "topics"
    category = "categories"

[params]
    defaultDescription = "Another random programmer's blog"
    defaultKeywords = "nicholas johns,home,website,blog,golang,docker,php"
    tagline = "Another random programmer's blog"
	theme = "theme-base-08"
	highlight = "sunburst"
    googleAnalytics = "UA-43022143-1"
    gravatarHash = "dc6e8fcb5d2bf3a94b850f295b4102c6"
	github = "https://github.com/taion809"
	twitter = "https://twitter.com/taion809"
